###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

  postgres:
    image: postgres:alpine
    container_name: reception-postgres
    working_dir: /application
    volumes:
      - .:/application
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hero
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  php-fpm:
    build: ./
    container_name: reception-php-fpm
    working_dir: /application
    volumes:
      - .:/application

  webserver:
    image: nginx:alpine
    container_name: reception-webserver
    working_dir: /application
    volumes:
      - .:/application
      - .:/etc/nginx/conf.d
      - ./nginx:/var/log/nginx
    ports:
      - "80:80"
